/**
 * `easyoref init` — Interactive setup wizard
 *
 * Walks user through:
 *   1. Language selection (ru/en/he)
 *   2. Bot token input + validation
 *   3. Chat ID input
 *   4. Area selection (checkbox)
 *   5. Generates .env file
 */

import { checkbox, input, password, select } from "@inquirer/prompts";
import chalk from "chalk";
import { Bot } from "grammy";
import { writeFileSync } from "node:fs";
import { AREA_CHOICES } from "../data/areas.js";

export async function init(): Promise<void> {
  // ── Step 0: Language ───────────────────────────────────

  const language = await select({
    message: "🌍 Message language / Язык сообщений / שפת ההודעות:",
    choices: [
      { name: "Русский", value: "ru" },
      { name: "English", value: "en" },
      { name: "עברית", value: "he" },
    ],
  });

  const t = translations[language as keyof typeof translations];

  // ── Step 1: Bot Token ──────────────────────────────────

  const botToken = await password({
    message: t.botTokenPrompt,
    validate: (val) => {
      if (!val || val.length < 10) return t.botTokenRequired;
      if (!val.includes(":")) return t.botTokenFormat;
      return true;
    },
  });

  // Validate token by calling Telegram API
  console.log(chalk.dim(t.validating));
  try {
    const bot = new Bot(botToken);
    const me = await bot.api.getMe();
    console.log(chalk.green(`  ✅ ${t.botVerified}: @${me.username}`));
  } catch {
    console.log(chalk.yellow(`  ⚠️  ${t.botVerifyFailed}`));
  }

  // ── Step 2: Chat ID ────────────────────────────────────

  const chatId = await input({
    message: t.chatIdPrompt,
    validate: (val) => {
      if (!val) return t.chatIdRequired;
      // Allow negative numbers (groups) and positive (DMs)
      if (!/^-?\d+$/.test(val)) return t.chatIdFormat;
      return true;
    },
  });

  // ── Step 3: Areas ──────────────────────────────────────

  const areas = await checkbox({
    message: t.areasPrompt,
    choices: AREA_CHOICES,
    required: true,
  });

  // ── Step 4: Write .env ─────────────────────────────────

  const envContent = [
    "# EasyOref Configuration",
    `# Generated by @easyoref/cli on ${new Date().toISOString().split("T")[0]}`,
    "",
    `BOT_TOKEN=${botToken}`,
    `CHAT_ID=${chatId}`,
    `AREAS=${areas.join(",")}`,
    `LANGUAGE=${language}`,
    "HEALTH_PORT=3100",
    "",
  ].join("\n");

  writeFileSync(".env", envContent, "utf-8");

  console.log("");
  console.log(chalk.green.bold(`✅ ${t.configSaved}`));
  console.log("");
  console.log(chalk.dim(t.nextSteps));
  console.log(
    `  ${chalk.cyan("docker compose up -d")}  ${chalk.dim("(Docker)")}`,
  );
  console.log(
    `  ${chalk.cyan("npm start")}             ${chalk.dim("(Node.js)")}`,
  );
  console.log("");
}

// ── i18n for the wizard itself ───────────────────────────

const translations = {
  ru: {
    botTokenPrompt: "🤖 Токен бота (от @BotFather):",
    botTokenRequired: "Токен обязателен",
    botTokenFormat: "Формат: 123456:ABC-DEF...",
    validating: "  Проверяем токен...",
    botVerified: "Бот найден",
    botVerifyFailed: "Не удалось проверить токен (продолжаем)",
    chatIdPrompt: "💬 Chat ID группы (отрицательное число):",
    chatIdRequired: "Chat ID обязателен",
    chatIdFormat: "Chat ID — число (отрицательное для групп)",
    areasPrompt: "📍 Выберите районы для мониторинга (пробел = выбрать):",
    configSaved: "Конфигурация сохранена в .env",
    nextSteps: "Следующий шаг — запустите бота:",
  },
  en: {
    botTokenPrompt: "🤖 Bot Token (from @BotFather):",
    botTokenRequired: "Token is required",
    botTokenFormat: "Format: 123456:ABC-DEF...",
    validating: "  Validating token...",
    botVerified: "Bot found",
    botVerifyFailed: "Could not verify token (continuing anyway)",
    chatIdPrompt: "💬 Chat ID (negative number for groups):",
    chatIdRequired: "Chat ID is required",
    chatIdFormat: "Chat ID must be a number (negative for groups)",
    areasPrompt: "📍 Select areas to monitor (space = toggle):",
    configSaved: "Config saved to .env",
    nextSteps: "Next step — start the bot:",
  },
  he: {
    botTokenPrompt: "🤖 טוקן בוט (מ-@BotFather):",
    botTokenRequired: "טוקן נדרש",
    botTokenFormat: "פורמט: 123456:ABC-DEF...",
    validating: "  מאמת טוקן...",
    botVerified: "בוט נמצא",
    botVerifyFailed: "לא ניתן לאמת את הטוקן (ממשיכים)",
    chatIdPrompt: "💬 Chat ID (מספר שלילי לקבוצות):",
    chatIdRequired: "Chat ID נדרש",
    chatIdFormat: "Chat ID חייב להיות מספר (שלילי לקבוצות)",
    areasPrompt: "📍 בחר אזורים לניטור (רווח = בחירה):",
    configSaved: "הגדרות נשמרו ל-.env",
    nextSteps: "שלב הבא — הפעל את הבוט:",
  },
};
